name: "custom-action-meme"
description: "Agrega un meme al readme dependiendo del resultado de los tests"
author: "Your Name"
inputs:
  frase_positiva:
    description: "Frase positiva a utilizar"
    required: true
   

  frase_negativa:
    description: "Frase negativa a utilizar"
    required: true
  resultado_tests:
    description: "Resultado de los tests"
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
