name: Deploy react app

on:
  push:
    branches:
      - react_app_deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
        #subida de artefactos creados 
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
   
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy React App
      #desplegar los artefactos descargados en rurge e iniciar sesion en surje para luego  iniciar el dominio
        run: |
          npm install -g surge
          surge --project ./build --domain https://react-app-deploy.surge.sh
          

