name: Deploy react app

on:
  push:
    branches:
      - react_app_deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
        #subida de artefactos creados 
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
   
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy React App
      #Crear cuenta en surge.sh y crear un token y un dominio y usuario
        uses: peaceiris/actions-surge@v3
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          surge_domain: ${{ secrets.SURGE_DOMAIN }}
          surge_login: ${{ secrets.SURGE_LOGIN }}
          surge_project: ./build
          surge_options: --token ${{ secrets.SURGE_TOKEN }} --domain ${{ secrets.SURGE_DOMAIN }} --login ${{ secrets.SURGE_LOGIN }}