name: Deploy react app

on:
  push:
    branches:
      - react_app_deploy

jobs: 
  build: #JOB 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
        #subida de artefactos creados 
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy: #JOB
    needs: build
    runs-on: ubuntu-latest
    steps:
   
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy React App
        uses: dswistowski/surge-sh-action@v1 
        with:
           domain: 'jessica-2daw-despliegues.surge.sh'
           token: ${{ secrets.SURGE_TOKEN }}
