name: Deploy react app

on:
  push:
    branches:
      - react_app_deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v2
      
        run: |
          npm install
          npm run build --if-present
        #subida de artefactos creados
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
   
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy React App
      #desplegar los artefactos descargados en rurge
        uses: dswistowski/surge-sh-action@v2
        with:
          domain: ${{ secrets.surge_domain }}
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

