name:  main_workflow
on: [push]

jobs:
  linter-execution: #job
    runs-on: ubuntu-latest
    steps: #step

        - name: Checkout code
          uses: actions/checkout@v3
   

        - name: Linter execution
          uses: github/super-linter@v4

          env: 
            
            DEFAULT_BRANCH: "nodejs_linter_job"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: /
            JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true
       
 