name: "modify_readme"

on: [push]

jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ejecutar tests
        run: |
          npm install
          npm test
      - name: Guardar resultado de los tests
        run: echo "::set-output name=resultado_tests::$TEST_RESULT"
  agregar_meme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Agregar meme al readme
        uses: ./
        env:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sables"
          resultado_tests: ${{ job.ejecutar_tests.outputs.resultado_tests }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_IDENTIFICACION_GITHUB }}
         

          run: |
            npm install
            node index.js
      

      - name: Commit and push
       
        run: |
          git config  user.name  Jessica-Reche
          git config  user.email jessikareix20@gmail.com
          git add .
          git commit -m"Agregar meme al readme"
          git push https://$TOKEN_IDENTIFICACION_GITHUB@github.com/Jessica-Reche/githubActions_examples.git

          

          
