name: "modify_readme"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      resultado_tests: ${{ steps.test_job.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test_job
        id: test_job
        run: |
          npm install
          npm test
          result=$?
          #resultado de la ejecución de los tests
          echo "::set-output name=result::$result"
     
  agregar_meme:
    runs-on: ubuntu-latest 
    if: ${{ always() }}
    needs: test
    outputs:
      resultado_tests: ${{ steps.obtener_resultado.outputs.resultado_tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Obtener resultado de los tests
        id: obtener_resultado
        run: |
            #si no recibe parametros el output se crea otro output en este job con el valor 1
            if [ -z "${{ needs.test.outputs.resultado_tests }}" ]; then
               echo "::set-output name=resultado_tests::1"
            else
                echo "::set-output name=resultado_tests::0"
              fi
           
      - name: Agregar meme al readme
        uses: ./
        with:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sabes"
          resultado_tests: ${{ steps.obtener_resultado.outputs.resultado_tests }}
      - name: Ejecutar código
        run: |
          npm install
          npm start
      - name: Commit and push
        run: |
          git config  user.name  Jessica-Reche
          git config  user.email jessikareix20@gmail.com
          git add .
          git commit -m"Agregar meme al readme"
          git push https://${{ secrets.TOKEN_GITHUB_JESSICA }}@github.com/Jessica-Reche/githubActions_examples.git