name: "modify_readme"

on: [push]

jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ejecutar tests
        run: |
          npm install
          npm test 
      # guardar el resultado de los tests
      - name: Guardar resultado de los tests
        id: ejecutar_tests
        run: |
          echo "::set-output name=status::$(npm test | grep -oP '(?<=tests: )\d+(?= passing)')" 
        
  agregar_meme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Agregar meme al readme
        uses: ./
        env:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sables"
          resultado_tests: ${{ steps.ejecutar_tests.outputs.status }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB_JESSICA }}
         

          run: |
            npm install
            node index.js
      

      - name: Commit and push
       
        run: |
          git config  user.name  Jessica-Reche
          git config  user.email jessikareix20@gmail.com
          git add .
          git commit -m"Agregar meme al readme"
          git push https://$TOKEN_GITHUB_JESSICA@github.com/Jessica-Reche/githubActions_examples.git

           
 
          
