name: "modify_readme"

on: [push]

jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest 
    env:
      TOKEN_GITHUB_JESSICA: ${{ secrets.TOKEN_GITHUB_JESSICA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ejecutar tests
        run: |
          npm install
          npm test
     
      #guardar el estado de los tests en una variable para usarlo luego
      - name: Guardar estado de los tests en una variable para usarlo en el job siguiente
        id: tests
        run: |
          echo "::set-output name=resultado_tests::$(npm test)"
  agregar_meme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Agregar meme al readme
        uses: ./
        with:
         frase_positiva: 'Los tests han funcionado y lo sabes'
         frase_negativa: 'Los tests han fallado y lo sabes'
         resultado_tests: ${{ steps.ejecutar_tests.outputs.resultado_tests }}

      - name: Commit and push
       
        run: |
          git config  user.name  Jessica-Reche
          git config  user.email jessikareix20@gmail.com
          git add .
          git commit -m"Agregar meme al readme"
          git push https://$TOKEN_GITHUB_JESSICA@github.com/Jessica-Reche/githubActions_examples.git

           
 
          
