name: "modify_readme"

on: [push]

jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ejecutar tests
        run: |
          npm install
          npm run build --if-present
          npm test 
      # guardar el resultado de los tests
      - name: Guardar resultado de los test en artefactos
        uses: actions/upload-artifact@v2
        with:
          name: ejecutar tests
          path: ejecutar tests
      
     
  agregar_meme:
    runs-on: ubuntu-latest
    needs: ejecutar_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  # descargar los artefactos
      - name: Descargar artefactos
     #Descargar los artefactos de la ejecución de los tests
        uses: actions/download-artifact@v2
        with:
          name: ejecutar tests
          path: ejecutar tests
       
        #Usar el resultado de los tests
      - name: Usar el resultado de los tests desde el artefacto
        id: ejecutar_tests
        run: |
          echo "::set-output name=status::$(cat resultado_tests)"  
      
      - name: Agregar meme al readme
        uses: ./
        env:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sables"
          resultado_tests: ${{ steps.ejecutar_tests.outputs.status }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB_JESSICA }}
          run: |
            npm install
            node index.js
      - name: Commit and push 
        run: |
          git config  user.name  Jessica-Reche
          git config  user.email jessikareix20@gmail.com
          git add .
          git commit -m"Agregar meme al readme"
          git push https://$TOKEN_GITHUB_JESSICA@github.com/Jessica-Reche/githubActions_examples.git

           
 
          
