name: "modify_readme"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      resultado_tests: ${{ steps.test_job.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test_job
        id: test_job
        run: |
          npm install
          npm test
     
  agregar_meme:
    runs-on: ubuntu-latest 
    if: ${{ always() }}
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Agregar meme al readme
        uses: ./
        with:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sabes"
          resultado_tests: ${{ needs.test.outputs.resultado_tests }}
      - name: Commit and push
        run: |
          git config  user.name  Jessica-Reche
          git config  user.email jessikareix20@gmail.com
          git add .
          git commit -m"Agregar meme al readme"
          git push https://${{ secrets.TOKEN_GITHUB_JESSICA }}@github.com/Jessica-Reche/githubActions_examples.git